name: Generate and Push Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 毎日 0:00 UTC（日本時間 9:00 JST）に実行
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          clean: true
          fetch-depth: 1

      # sitemap.xml を生成
      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          # ルートページを追加
          echo "  <url><loc>https://hamuzon.github.io/</loc></url>" >> sitemap.xml

          # サブディレクトリを自動取得して URL を追加
          find . -type d ! -path "./.git*" ! -path "./.github*" ! -path "." | while read d; do
            url_path=$(echo "$d" | sed 's|^\./||')
            echo "  <url><loc>https://hamuzon.github.io/$url_path/</loc></url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      # Git 設定
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --local gc.auto 0

      # sitemap.xml を追加してコミット
      - name: Commit changes
        run: |
          git add sitemap.xml
          git diff --quiet || git commit -m "Update sitemap.xml"

      # push
      - name: Push changes
        run: git push origin main