name: Update sitemap.xml from public for multiple repos

# トリガー: main ブランチへの push または手動実行
on:
  push:
    branches:
      - main
  workflow_dispatch:

# GITHUB_TOKEN に書き込み権限を付与
permissions:
  contents: write

jobs:
  update-sitemaps:
    runs-on: ubuntu-24.04

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          clean: true
          fetch-depth: 1

      # リストに登録したサブリポジトリまたはディレクトリから sitemap をコピー
      - name: Copy sitemap.xml from public
        run: |
          # 対象リポジトリやディレクトリを配列で指定
          REPOS=(
            "."  # このリポジトリ自身
            "./another-repo"  # 別リポジトリ/ディレクトリの例
          )

          for repo in "${REPOS[@]}"; do
            echo "Processing $repo ..."
            cp "$repo/public/hamuzon.github.io-sitemap.xml" "$repo/sitemap.xml"
          done

      # Git 設定
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # sitemap.xml を追加してコミット
      - name: Commit changes
        run: |
          git add ./*/sitemap.xml sitemap.xml || true
          git commit -m "Update sitemap.xml from public" || echo "No changes to commit"

      # push
      - name: Push changes
        run: git push
