name: Generate and Push Sitemap

# トリガー設定
on:
  push:
    branches:
      - main
  workflow_dispatch:

# GitHub Token の権限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          clean: true
          fetch-depth: 1

      # 2. sitemap.xml を生成
      - name: Generate sitemap.xml
        run: |
          # XML ヘッダー
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          # ルートページを追加
          echo "  <url><loc>https://hamuzon.github.io/</loc></url>" >> sitemap.xml

          # サブディレクトリを取得して URL を追加
          for d in $(find . -maxdepth 1 -type d ! -name ".git" ! -name ".github" ! -name ".github.io"); do
            name=$(basename "$d")
            echo "  <url><loc>https://hamuzon.github.io/$name/</loc></url>" >> sitemap.xml
          done

          # XML フッター
          echo '</urlset>' >> sitemap.xml

      # 3. Git 設定
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --local gc.auto 0  # 自動ガベージコレクションを無効

      # 4. sitemap.xml をステージしてコミット
      - name: Commit changes
        run: |
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"

      # 5. リモートにプッシュ
      - name: Push changes
        run: git push origin main